// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnzvtjmlqngajkwuvhvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuenZ0am1scW5nYWprd3V2aHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjQyMTgsImV4cCI6MjA3NDE0MDIxOH0.IvzT2wuPnbfvRXzxXThz5tLot5p4suJ-LxK0cMpxaIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});