name: Deploy to Hostinger (gslubricants.com)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and build (Vite/React)
        run: |
          npm ci
          npm run build

      - name: List build output
        run: ls -la dist
      
      - name: Deploy build folder to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.H_FTP_HOST }}
          username: ${{ secrets.H_FTP_USER }}
          password: ${{ secrets.H_FTP_PASS }}
          protocol: ftp
          port: 21
          local-dir: ./dist/
          server-dir: /                     # this FTP user’s home IS gslubricants.com/public_html
          dangerous-clean-slate: true
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
