name: Deploy to Hostinger (FTP)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and build (Vite/React)
        run: |
          npm ci
          npm run build

      - name: List build output
        run: ls -la dist
      
      - name: Deploy dist/ to Hostinger webroot
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./dist/                          # must end with /
          server-dir: /home/u898968340/domains/peachpuff-kangaroo-729636.hostingersite.com/public_html/  # <-- YOUR exact path with trailing /
          dangerous-clean-slate: true




